name: Generate OJS Hashes

on:
  workflow_dispatch:
    inputs:
      ojs_version:
        description: 'OJS Version (e.g., 3.4.0-5)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set OJS Version
      id: get_version
      run: echo "VERSION=${{ github.event.inputs.ojs_version }}" >> $GITHUB_ENV

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Download and Extract OJS
      run: |
        wget "https://pkp.sfu.ca/ojs/download/ojs-${{ env.VERSION }}.tar.gz"
        tar -xzf "ojs-${{ env.VERSION }}.tar.gz"

    - name: Generate Hashes JSON
      run: |
        cd "ojs-${{ env.VERSION }}"
        find . -type f ! -name 'config.TEMPLATE.inc.php' -print0 | xargs -0 sha256sum | \
        awk '{sub(/^\.\//, "", $2); printf "{\"%s\":\"%s\"}\n", $2, $1}' | \
        jq -s 'add' > "..ojs-${{ env.VERSION }}.json"
        cd ..

    - name: Upload hashes as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ojs-hashes
        path: hashes-${{ env.VERSION }}.json
